/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessRights = { 'Read' : null } |
  { 'ReadWrite' : null } |
  { 'ReadWriteManage' : null };
export interface ByteBuf { 'inner' : Uint8Array }
export interface EncryptedMapData {
  'access_control' : Array<[Principal, AccessRights]>,
  'keyvals' : Array<[ByteBuf, ByteBuf]>,
  'map_name' : ByteBuf,
  'map_owner' : Principal,
}
export type Result = { 'Ok' : null } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : [] | [AccessRights] } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : bigint } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : Array<ByteBuf> } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : [] | [ByteBuf] } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : Array<TrashedItem> } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Array<[Principal, AccessRights]> } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : ByteBuf } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : Array<[ByteBuf, ByteBuf]> } |
  { 'Err' : string };
export interface TrashedItem {
  'value' : ByteBuf,
  'map_key' : ByteBuf,
  'deleted_at' : bigint,
  'deleted_by' : Principal,
}
export interface VaultName {
  'owner' : Principal,
  'display_name' : string,
  'map_name' : ByteBuf,
}
export interface VaultSummary {
  'owner' : Principal,
  'item_keys' : Array<ByteBuf>,
  'access_control' : Array<[Principal, AccessRights]>,
  'trashed' : bigint,
  'my_rights' : [] | [AccessRights],
  'digest' : ByteBuf,
  'map_name' : ByteBuf,
}
export interface _SERVICE {
  'get_accessible_shared_map_names' : ActorMethod<
    [],
    Array<[Principal, ByteBuf]>
  >,
  'get_all_accessible_encrypted_maps' : ActorMethod<
    [],
    Array<EncryptedMapData>
  >,
  'get_all_accessible_encrypted_values' : ActorMethod<
    [],
    Array<[[Principal, ByteBuf], Array<[ByteBuf, ByteBuf]>]>
  >,
  'get_encrypted_value' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_4>,
  'get_encrypted_values_for_map' : ActorMethod<[Principal, ByteBuf], Result_8>,
  'get_encrypted_vetkey' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_7>,
  'get_owned_non_empty_map_names' : ActorMethod<[], Array<ByteBuf>>,
  'get_shared_user_access_for_map' : ActorMethod<
    [Principal, ByteBuf],
    Result_6
  >,
  /**
   * / What is recoverable in one vault, with each item's ciphertext so a client
   * / can show what it was rather than only when it went. See `TrashedItem` for
   * / why returning values here is not the thing #14 removed from the poll.
   * /
   * / Visible to the vault's owner, and to whoever deleted the entry. Not to
   * / every reader: a collaborator added *after* a deletion would otherwise be
   * / shown a secret that was destroyed before they had any access to it, which
   * / permanent deletion never allowed.
   */
  'get_trash' : ActorMethod<[Principal, ByteBuf], Result_5>,
  'get_user_rights' : ActorMethod<[Principal, ByteBuf, Principal], Result_1>,
  /**
   * / Display names for every vault the caller can see, owned and shared.
   * /
   * / One query and **zero key derivations** — the hard requirement. The sidebar
   * / must render names without opening a vault, or lazy loading is undone. Rows
   * / for vaults the caller cannot see are never returned, so a stray row is
   * / invisible as well as harmless.
   */
  'get_vault_names' : ActorMethod<[], Array<VaultName>>,
  'get_vault_summaries' : ActorMethod<[], Array<VaultSummary>>,
  'get_vetkey_verification_key' : ActorMethod<[], ByteBuf>,
  'insert_encrypted_value' : ActorMethod<
    [Principal, ByteBuf, ByteBuf, ByteBuf],
    Result_4
  >,
  'remove_encrypted_value' : ActorMethod<
    [Principal, ByteBuf, ByteBuf],
    Result_4
  >,
  'remove_map_values' : ActorMethod<[Principal, ByteBuf], Result_3>,
  'remove_user' : ActorMethod<[Principal, ByteBuf, Principal], Result_1>,
  /**
   * / Put one item back. Authorization is the library's: this is an insert, so a
   * / caller without write rights is refused there and the entry stays put.
   */
  'restore_trashed_value' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result>,
  /**
   * / Put a whole vault back, for undoing a wipe without one call per item.
   */
  'restore_trashed_values' : ActorMethod<[Principal, ByteBuf], Result_2>,
  'set_user_rights' : ActorMethod<
    [Principal, ByteBuf, Principal, AccessRights],
    Result_1
  >,
  /**
   * / Rename one of *your own* vaults, or clear the name by passing "".
   * /
   * / Owner-only by construction: the row is keyed on `msg.caller`, so there is
   * / no way to address someone else's vault. A collaborator renaming a shared
   * / vault for everyone would be a surprise, and this makes it unrepresentable
   * / rather than merely checked.
   */
  'set_vault_name' : ActorMethod<[ByteBuf, string], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];