/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessRights = { 'Read' : null } |
  { 'ReadWrite' : null } |
  { 'ReadWriteManage' : null };
export interface ByteBuf { 'inner' : Uint8Array }
export interface EncryptedMapData {
  'access_control' : Array<[Principal, AccessRights]>,
  'keyvals' : Array<[ByteBuf, ByteBuf]>,
  'map_name' : ByteBuf,
  'map_owner' : Principal,
}
export type Result = { 'Ok' : null } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : [] | [AccessRights] } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : bigint } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : Array<ByteBuf> } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : [] | [ByteBuf] } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : Array<TrashedItem> } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Array<[Principal, AccessRights]> } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : Array<Version> } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : ByteBuf } |
  { 'Err' : string };
export type Result_9 = { 'Ok' : Array<[ByteBuf, ByteBuf]> } |
  { 'Err' : string };
export interface TrashedItem {
  'seq' : bigint,
  'value' : ByteBuf,
  'map_key' : ByteBuf,
  'deleted_at' : bigint,
  'deleted_by' : Principal,
}
export interface VaultName {
  'owner' : Principal,
  'display_name' : string,
  'map_name' : ByteBuf,
}
export interface VaultSummary {
  'trash_digest' : ByteBuf,
  'owner' : Principal,
  'item_keys' : Array<ByteBuf>,
  'access_control' : Array<[Principal, AccessRights]>,
  'trashed' : bigint,
  'my_rights' : [] | [AccessRights],
  'digest' : ByteBuf,
  'map_name' : ByteBuf,
}
export interface Version {
  'at' : bigint,
  'by' : Principal,
  'seq' : bigint,
  'value' : [] | [ByteBuf],
  'kind' : VersionKind,
}
export type VersionKind = { 'Edited' : null } |
  { 'Restored' : null } |
  { 'Deleted' : null };
export interface _SERVICE {
  /**
   * / Make a vault's deletions unrecoverable now, rather than waiting out their
   * / 90 days.
   * /
   * / The counterpart to trash being vault-scoped: sharing a vault hands the
   * / grantee its trash too, so there has to be a way to take a secret out of
   * / reach *before* granting access. Without this the exposure would have no
   * / remedy but time.
   * /
   * / **Owner only.** The earlier rule was write access, on the reasoning that
   * / `ReadWrite` already destroys a vault's contents through
   * / `remove_map_values`. Trash made that false: a writer can empty a vault but
   * / no longer destroy it, so this is the only true destruction and gating it on
   * / write hands back the power trash removed. Measured — a collaborator could
   * / wipe a vault they did not own, discard its trash, and the vault then
   * / dropped out of the owner's listing.
   * /
   * / Scoped to secrets with no live value, so it empties the trash without
   * / touching the version history of secrets that are still there.
   */
  'discard_trash' : ActorMethod<[Principal, ByteBuf], Result_2>,
  /**
   * / Drop the stored versions of one secret, keeping the secret itself.
   * /
   * / The owner's way to reclaim space, or to stop keeping a secret's earlier
   * / values, without a retention policy guessing on their behalf (#38).
   * /
   * / Clears the ciphertext and **keeps the events**, so "edited by X at T"
   * / survives. Otherwise pruning would be a way to launder the audit trail.
   * /
   * / Not restricted to live secrets. Applied to a deleted one it clears the
   * / version the trash was offering, and `get_trash` then skips the group —
   * / a group whose newest event carries no value has nothing to put back. So
   * / this doubles as "delete this one trashed secret for good", which is the
   * / per-secret counterpart to `discard_trash`. Owner-only for that reason:
   * / it is a destruction, not housekeeping.
   */
  'drop_history' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_2>,
  'get_accessible_shared_map_names' : ActorMethod<
    [],
    Array<[Principal, ByteBuf]>
  >,
  'get_all_accessible_encrypted_maps' : ActorMethod<
    [],
    Array<EncryptedMapData>
  >,
  'get_all_accessible_encrypted_values' : ActorMethod<
    [],
    Array<[[Principal, ByteBuf], Array<[ByteBuf, ByteBuf]>]>
  >,
  'get_encrypted_value' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_4>,
  'get_encrypted_values_for_map' : ActorMethod<[Principal, ByteBuf], Result_9>,
  'get_encrypted_vetkey' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_8>,
  /**
   * / Every recorded version of one secret, oldest first.
   * /
   * / Visible to everyone who can read the vault, on the same reasoning as
   * / `get_trash`: a reader can already read the current value, so earlier
   * / values of the same secret are not a wider class of information. It does
   * / mean a member added later sees versions written before they arrived —
   * / deliberate, and `drop_history` is the owner's remedy.
   * /
   * / Not on the poll. Values ride this because it is user-initiated and scoped
   * / to one secret; #14's rule is that nothing automatic carries ciphertext.
   */
  'get_history' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_7>,
  'get_owned_non_empty_map_names' : ActorMethod<[], Array<ByteBuf>>,
  'get_shared_user_access_for_map' : ActorMethod<
    [Principal, ByteBuf],
    Result_6
  >,
  /**
   * / What is recoverable in one vault, with each item's ciphertext so a client
   * / can show what it was rather than only when it went. See `TrashedItem` for
   * / why returning values here is not the thing #14 removed from the poll.
   * /
   * / Visible to everyone who can read the vault. What that changes differs by
   * / access level, and the difference is worth stating precisely.
   * /
   * / For a member who can **write**, nothing new is disclosed:
   * / `restore_trashed_values` puts back every entry in the vault on write
   * / access alone, so they could already recover an entry withheld from the
   * / listing and then read it. Listing less than the restore path recovers
   * / hides entries without keeping them out of reach.
   * /
   * / For a `Read` member it **is** a new disclosure. They hold the vault key,
   * / so the ciphertext returned here decrypts, and one added after a deletion
   * / can read a secret destroyed before they had any access — which no path
   * / reached before. Accepted deliberately, not incidentally: trash belongs to
   * / the vault, the share dialog says how many entries a grantee would
   * / inherit, and `discard_trash` is the remedy.
   * /
   * / The alternative was to filter the restore path by the same predicate,
   * / making owner-or-deleter real rather than cosmetic — one line, since
   * / `restore_trashed_values` has the entry in hand. Rejected because it turns
   * / `deletedBy` into authorization data rather than display, and because it
   * / denies a team the case a shared vault exists for: recovering what a
   * / colleague who has since left deleted.
   */
  'get_trash' : ActorMethod<[Principal, ByteBuf], Result_5>,
  'get_user_rights' : ActorMethod<[Principal, ByteBuf, Principal], Result_1>,
  /**
   * / Display names for every vault the caller can see, owned and shared.
   * /
   * / One query and **zero key derivations** — the hard requirement. The sidebar
   * / must render names without opening a vault, or lazy loading is undone. Rows
   * / for vaults the caller cannot see are never returned, so a stray row is
   * / invisible as well as harmless.
   */
  'get_vault_names' : ActorMethod<[], Array<VaultName>>,
  'get_vault_summaries' : ActorMethod<[], Array<VaultSummary>>,
  'get_vetkey_verification_key' : ActorMethod<[], ByteBuf>,
  'insert_encrypted_value' : ActorMethod<
    [Principal, ByteBuf, ByteBuf, ByteBuf],
    Result_4
  >,
  'remove_encrypted_value' : ActorMethod<
    [Principal, ByteBuf, ByteBuf],
    Result_4
  >,
  'remove_map_values' : ActorMethod<[Principal, ByteBuf], Result_3>,
  'remove_user' : ActorMethod<[Principal, ByteBuf, Principal], Result_1>,
  /**
   * / Put one version back, addressed by its event.
   * /
   * / Authorization is the library's: this is an insert, so a caller without
   * / write rights is refused there and nothing is recorded.
   * /
   * / Removes nothing. The row stays, and the secret leaves the trash because it
   * / has a live value again — which is what keeps a writer unable to destroy
   * / anything, and what lets a recovered secret keep its history.
   */
  'restore_trashed_value' : ActorMethod<[Principal, ByteBuf, bigint], Result>,
  /**
   * / Put a whole vault's trash back, for undoing a wipe without one call per
   * / item.
   * /
   * / Authorization is the library's, per insert, so write access is what this
   * / needs and a reader is refused on the first entry. It restores every
   * / entry the trash lists rather than only the caller's own, which is why
   * / `get_trash` lists the same set — see its comment.
   * /
   * / Restores the **newest** version of each deleted secret. A vault can hold
   * / several events for one map key, and replaying them all would mean each
   * / insert overwriting the last — silent loss inside a recovery operation.
   * / `History.trash` already yields one row per key, which is that row.
   */
  'restore_trashed_values' : ActorMethod<[Principal, ByteBuf], Result_2>,
  'set_user_rights' : ActorMethod<
    [Principal, ByteBuf, Principal, AccessRights],
    Result_1
  >,
  /**
   * / Rename one of *your own* vaults, or clear the name by passing "".
   * /
   * / Owner-only by construction: the row is keyed on `msg.caller`, so there is
   * / no way to address someone else's vault. A collaborator renaming a shared
   * / vault for everyone would be a surprise, and this makes it unrepresentable
   * / rather than merely checked.
   */
  'set_vault_name' : ActorMethod<[ByteBuf, string], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];