/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const ByteBuf = IDL.Record({ 'inner' : IDL.Vec(IDL.Nat8) });
  const Result_2 = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : IDL.Text });
  const AccessRights = IDL.Variant({
    'Read' : IDL.Null,
    'ReadWrite' : IDL.Null,
    'ReadWriteManage' : IDL.Null,
  });
  const EncryptedMapData = IDL.Record({
    'access_control' : IDL.Vec(IDL.Tuple(IDL.Principal, AccessRights)),
    'keyvals' : IDL.Vec(IDL.Tuple(ByteBuf, ByteBuf)),
    'map_name' : ByteBuf,
    'map_owner' : IDL.Principal,
  });
  const Result_4 = IDL.Variant({ 'Ok' : IDL.Opt(ByteBuf), 'Err' : IDL.Text });
  const Result_9 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Tuple(ByteBuf, ByteBuf)),
    'Err' : IDL.Text,
  });
  const Result_8 = IDL.Variant({ 'Ok' : ByteBuf, 'Err' : IDL.Text });
  const VersionKind = IDL.Variant({
    'Edited' : IDL.Null,
    'Restored' : IDL.Null,
    'Deleted' : IDL.Null,
  });
  const Version = IDL.Record({
    'at' : IDL.Nat64,
    'by' : IDL.Principal,
    'seq' : IDL.Nat64,
    'value' : IDL.Opt(ByteBuf),
    'kind' : VersionKind,
  });
  const Result_7 = IDL.Variant({ 'Ok' : IDL.Vec(Version), 'Err' : IDL.Text });
  const Result_6 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Tuple(IDL.Principal, AccessRights)),
    'Err' : IDL.Text,
  });
  const TrashedItem = IDL.Record({
    'seq' : IDL.Nat64,
    'value' : ByteBuf,
    'map_key' : ByteBuf,
    'deleted_at' : IDL.Nat64,
    'deleted_by' : IDL.Principal,
  });
  const Result_5 = IDL.Variant({
    'Ok' : IDL.Vec(TrashedItem),
    'Err' : IDL.Text,
  });
  const Result_1 = IDL.Variant({
    'Ok' : IDL.Opt(AccessRights),
    'Err' : IDL.Text,
  });
  const VaultName = IDL.Record({
    'owner' : IDL.Principal,
    'display_name' : IDL.Text,
    'map_name' : ByteBuf,
  });
  const VaultSummary = IDL.Record({
    'trash_digest' : ByteBuf,
    'owner' : IDL.Principal,
    'item_keys' : IDL.Vec(ByteBuf),
    'access_control' : IDL.Vec(IDL.Tuple(IDL.Principal, AccessRights)),
    'trashed' : IDL.Nat,
    'my_rights' : IDL.Opt(AccessRights),
    'digest' : ByteBuf,
    'map_name' : ByteBuf,
  });
  const Result_3 = IDL.Variant({ 'Ok' : IDL.Vec(ByteBuf), 'Err' : IDL.Text });
  const Result = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  
  return IDL.Service({
    'discard_trash' : IDL.Func([IDL.Principal, ByteBuf], [Result_2], []),
    'drop_history' : IDL.Func(
        [IDL.Principal, ByteBuf, ByteBuf],
        [Result_2],
        [],
      ),
    'get_accessible_shared_map_names' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ByteBuf))],
        ['query'],
      ),
    'get_all_accessible_encrypted_maps' : IDL.Func(
        [],
        [IDL.Vec(EncryptedMapData)],
        ['query'],
      ),
    'get_all_accessible_encrypted_values' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Tuple(IDL.Principal, ByteBuf),
              IDL.Vec(IDL.Tuple(ByteBuf, ByteBuf)),
            )
          ),
        ],
        ['query'],
      ),
    'get_encrypted_value' : IDL.Func(
        [IDL.Principal, ByteBuf, ByteBuf],
        [Result_4],
        ['query'],
      ),
    'get_encrypted_values_for_map' : IDL.Func(
        [IDL.Principal, ByteBuf],
        [Result_9],
        ['query'],
      ),
    'get_encrypted_vetkey' : IDL.Func(
        [IDL.Principal, ByteBuf, ByteBuf],
        [Result_8],
        [],
      ),
    'get_history' : IDL.Func(
        [IDL.Principal, ByteBuf, ByteBuf],
        [Result_7],
        ['query'],
      ),
    'get_owned_non_empty_map_names' : IDL.Func(
        [],
        [IDL.Vec(ByteBuf)],
        ['query'],
      ),
    'get_shared_user_access_for_map' : IDL.Func(
        [IDL.Principal, ByteBuf],
        [Result_6],
        ['query'],
      ),
    'get_trash' : IDL.Func([IDL.Principal, ByteBuf], [Result_5], ['query']),
    'get_user_rights' : IDL.Func(
        [IDL.Principal, ByteBuf, IDL.Principal],
        [Result_1],
        ['query'],
      ),
    'get_vault_names' : IDL.Func([], [IDL.Vec(VaultName)], ['query']),
    'get_vault_summaries' : IDL.Func([], [IDL.Vec(VaultSummary)], ['query']),
    'get_vetkey_verification_key' : IDL.Func([], [ByteBuf], []),
    'insert_encrypted_value' : IDL.Func(
        [IDL.Principal, ByteBuf, ByteBuf, ByteBuf],
        [Result_4],
        [],
      ),
    'remove_encrypted_value' : IDL.Func(
        [IDL.Principal, ByteBuf, ByteBuf],
        [Result_4],
        [],
      ),
    'remove_map_values' : IDL.Func([IDL.Principal, ByteBuf], [Result_3], []),
    'remove_user' : IDL.Func(
        [IDL.Principal, ByteBuf, IDL.Principal],
        [Result_1],
        [],
      ),
    'restore_trashed_value' : IDL.Func(
        [IDL.Principal, ByteBuf, IDL.Nat64],
        [Result],
        [],
      ),
    'restore_trashed_values' : IDL.Func(
        [IDL.Principal, ByteBuf],
        [Result_2],
        [],
      ),
    'set_user_rights' : IDL.Func(
        [IDL.Principal, ByteBuf, IDL.Principal, AccessRights],
        [Result_1],
        [],
      ),
    'set_vault_name' : IDL.Func([ByteBuf, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };