/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessRights = { 'Read' : null } |
  { 'ReadWrite' : null } |
  { 'ReadWriteManage' : null };
export interface ByteBuf { 'inner' : Uint8Array }
export interface EncryptedMapData {
  'access_control' : Array<[Principal, AccessRights]>,
  'keyvals' : Array<[ByteBuf, ByteBuf]>,
  'map_name' : ByteBuf,
  'map_owner' : Principal,
}
export interface ItemSummary {
  'updated_at' : bigint,
  'map_key' : ByteBuf,
  'versions' : bigint,
}
export type Result = { 'Ok' : null } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : [] | [AccessRights] } |
  { 'Err' : string };
export type Result_10 = { 'Ok' : ByteBuf } |
  { 'Err' : string };
export type Result_11 = { 'Ok' : Array<[ByteBuf, ByteBuf]> } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : bigint } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : Array<ByteBuf> } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : [] | [ByteBuf] } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : Array<TrashedItem> } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Array<[Principal, AccessRights]> } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : ServiceHealth } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : Array<ItemSummary> } |
  { 'Err' : string };
export type Result_9 = { 'Ok' : Array<Version> } |
  { 'Err' : string };
export type ServiceHealth = { 'low_cycles' : null } |
  { 'funded' : null };
export interface TrashedItem {
  'seq' : bigint,
  'value' : ByteBuf,
  'map_key' : ByteBuf,
  'deleted_at' : bigint,
  'deleted_by' : Principal,
}
export interface VaultName {
  'owner' : Principal,
  'display_name' : string,
  'map_name' : ByteBuf,
}
export interface VaultSummary {
  'trash_digest' : ByteBuf,
  'owner' : Principal,
  'item_keys' : Array<ByteBuf>,
  'access_control' : Array<[Principal, AccessRights]>,
  'trashed' : bigint,
  'my_rights' : [] | [AccessRights],
  'digest' : ByteBuf,
  'map_name' : ByteBuf,
}
export interface Version {
  'at' : bigint,
  'by' : Principal,
  'seq' : bigint,
  'value' : [] | [ByteBuf],
  'kind' : VersionKind,
}
export type VersionKind = { 'Edited' : null } |
  { 'Restored' : null } |
  { 'Created' : null } |
  { 'Deleted' : null };
export interface _SERVICE {
  'create_vault' : ActorMethod<[ByteBuf, string], Result>,
  'delete_vault' : ActorMethod<[ByteBuf], Result>,
  'discard_trash' : ActorMethod<[Principal, ByteBuf], Result_2>,
  'drop_history' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_2>,
  'get_accessible_shared_map_names' : ActorMethod<
    [],
    Array<[Principal, ByteBuf]>
  >,
  'get_all_accessible_encrypted_maps' : ActorMethod<
    [],
    Array<EncryptedMapData>
  >,
  'get_all_accessible_encrypted_values' : ActorMethod<
    [],
    Array<[[Principal, ByteBuf], Array<[ByteBuf, ByteBuf]>]>
  >,
  'get_encrypted_value' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_4>,
  'get_encrypted_values_for_map' : ActorMethod<[Principal, ByteBuf], Result_11>,
  'get_encrypted_vetkey' : ActorMethod<
    [Principal, ByteBuf, ByteBuf],
    Result_10
  >,
  'get_history' : ActorMethod<[Principal, ByteBuf, ByteBuf], Result_9>,
  'get_item_summaries' : ActorMethod<[Principal, ByteBuf], Result_8>,
  'get_owned_non_empty_map_names' : ActorMethod<[], Array<ByteBuf>>,
  'get_owned_vaults' : ActorMethod<[], Array<ByteBuf>>,
  'get_service_health' : ActorMethod<[], Result_7>,
  'get_shared_user_access_for_map' : ActorMethod<
    [Principal, ByteBuf],
    Result_6
  >,
  'get_trash' : ActorMethod<[Principal, ByteBuf], Result_5>,
  'get_user_rights' : ActorMethod<[Principal, ByteBuf, Principal], Result_1>,
  'get_vault_names' : ActorMethod<[], Array<VaultName>>,
  'get_vault_summaries' : ActorMethod<[], Array<VaultSummary>>,
  'get_vetkey_verification_key' : ActorMethod<[], ByteBuf>,
  'insert_encrypted_value' : ActorMethod<
    [Principal, ByteBuf, ByteBuf, ByteBuf],
    Result_4
  >,
  'remove_encrypted_value' : ActorMethod<
    [Principal, ByteBuf, ByteBuf],
    Result_4
  >,
  'remove_map_values' : ActorMethod<[Principal, ByteBuf], Result_3>,
  'remove_user' : ActorMethod<[Principal, ByteBuf, Principal], Result_1>,
  'restore_trashed_values' : ActorMethod<[Principal, ByteBuf], Result_2>,
  'restore_version' : ActorMethod<[Principal, ByteBuf, bigint], Result>,
  'set_user_rights' : ActorMethod<
    [Principal, ByteBuf, Principal, AccessRights],
    Result_1
  >,
  'set_vault_name' : ActorMethod<[ByteBuf, string], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];